name: CI

on:
  push:
    branches:
      - develop
      - release
      - master
  pull_request:
    branches:
      - develop
      - release
      - master

  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Shell Linter
        uses: azohra/shell-linter@v0.4.0
        with:
          path: "greeting.sh"

      - name: Run Greeting
        run: ./greeting.sh $GITHUB_ACTOR